In [2]:
##Series
import pandas as pd
data = [10, 20, 30, 40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
##Access individual
print(series[2])

13

<ipython-input-6-9de569e5707e>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[2])

In [5]:
##
import pandas as pd
data = [11, 12, 13, 14]
series=pd.Series(data, index=['a','b','c','d'])
print(series)
print(series['c'])

a    11
b    12
c    13
d    14
dtype: int64
13

In [3]:
##Creating Datagram
data={'Name':['Alice','Bob','Charlie'], 'Age':[25,30,35]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [8]:
##Adding removing data
print(df['Name'])
print(df.iloc[1])
print(df.loc[1, 'Name'])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
Name    Bob
Age      30
Name: 1, dtype: object
Bob

In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
2 print(df.loc[0])
3 print(df.iloc[1])

In [9]:
##Group By
df = pd.DataFrame({'Catagory': ['cse','cse','eee','eee'],'Salary': [25, 30, 5, 35]})
print(df)
grouped = df.groupby('Catagory').sum()
print(grouped)

  Catagory  Salary
0      cse      25
1      cse      30
2      eee       5
3      eee      35
          Salary
Catagory
cse           55
eee           40

In [10]:
##Agregation Data
df = pd.DataFram({'A': [1, 2, 3],'B': [25, 30, 35]})
print(df.aggregate('min'))

AttributeError: module 'pandas' has no attribute 'DataFram'